type = "webpack"
webpack_config = "webpack.config.js"

[env.staging]
name = "covid-dev"
workers_dev = true

[env.production]
name = "covid"
zone_id = "ded9dec3d65cb1dbe6b9a084f9f02dbf"
route = "covid.cape.io/*"
workers_dev = false
